mysite/myapp/urls.py
from django.urls import path
from myapp.views import index, indexItem

app_name = "myapp"

urlpatterns = [
    #http://127.0.0.1:8000/myapp/
    path('', index),
    path("<int:my_id>/", indexItem, name="detail"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("myapp/", include("myapp.urls", namespace="myapp"))
]

mysite/myapp/models.py
from django.db import models

class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    description = models.CharField(max_length=200)

    def __str__(self):
        return self.name

mysite/myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Product

def index(request):
    items = Product.objects.all()
    context = {
        'items': items
    }
    return render(request, "myapp/index.html", context)

def indexItem(request, my_id):
    item = Product.objects.get(id=my_id)
    context = {
        'item': item
    }
    return render(request, "myapp/detail.html", context=context)

mysite/myapp/templates/myapp/detail.html
<h1>
    This detail page for : {{item.name}}
</h1>

mysite/myapp/templates/myapp/index.html
{% load static %}
<html>
    <head>
        <link rel="stylesheet" href="{% static 'myapp/style.css' %}">
    </head>
    <body>
        <h1>This is our index template</h1>
        <h4>
            <!--<a href="/myapp/items/{{item.id}}/">-->

            {% for item in items %}
            <a href="{% url 'myapp:detail' item.id %}">
            ID: {{item.id}} | Name: {{item.name}} | Price: {{item.price}} | Description: {{item.description}} <br/>
            <a>
            {% endfor %}
        </h4>
    </body>
</html>